### PR TITLE
Fixed SENTRY_BUILD_PATH resolution

### PR DESCRIPTION
**Pull request by moravcik**

### CODE REVIEW

**Comment by jakelumetta** [comment]
@moravcik We're getting this error.

```
-----> Build succeeded!
-----> SentrySourcemap app detected
-----> SENTRY_BUILD_PATH is missing or empty: unable to continue.
```

**Comment by jakelumetta** [comment]
CC @Trungi

**Comment by trungi** [comment]
Hi Jake, I'm sorry about it but this is just a fork from the repository https://github.com/khrome83/buildpack-sentry-sourcemaps and it might be better for you to use that one. This fork contains customizations with hardcoded paths for some of our apps so it will not work for you. If you need any help with the original repository just let me know, I can help.

**Comment by jakelumetta** [comment]
Thanks!

**Pull request merged**
